### ISSUE TITLE
RangeError: There is no position before the top-level node

### ISSUE THREAD

**Issue by gillangit** [hugs7/tiptap-extension-pagination#1]
hi, I'm interested in your code, I have a free project for my office to build a universal editor like Google Docs, the aim is to produce several documents from a form and edit using the editor, would you like to help me, if there is a cost, we can discuss it.

**Comment by hugs7** [comment]
At this stage, I've published this as a community plugin. I only needed an embedded editor with some specific functionality for a personal project - pagination happened to be one of the features I needed. I still don't know if this approach is viable, especially for longer documents and potentially as you add other functionality such as images. So you're free to use it but I'm not looking to build a universal editor like Google Docs which can handle much more functionality.

As per [this](https://github.com/ueberdosis/tiptap/issues/1870#issuecomment-2258629756) comment, Google Docs takes a very different approach. What you see is actually a rasterised picture not using the DOM. Tiptap adds DOM elements to form the document which is the main reason why "splitting" the tree into pages is very difficult.

**Comment by gillangit** [comment]
thanks for your atentions, why in my code not work?


import Link from "@tiptap/extension-link";
import Table from "@tiptap/extension-table";
import Image from "@tiptap/extension-image";
import StarterKit from "@tiptap/starter-kit";
import { Color } from "@tiptap/extension-color";
import TaskItem from "@tiptap/extension-task-item";
import TaskList from "@tiptap/extension-task-list";
import TableRow from "@tiptap/extension-table-row";
import Underline from "@tiptap/extension-underline";
import Highlight from "@tiptap/extension-highlight";
import TableCell from "@tiptap/extension-table-cell";
import TextStyle from "@tiptap/extension-text-style";
import TextAlign from "@tiptap/extension-text-align";
import Pagination from "tiptap-extension-pagination";
import FontFamily from "@tiptap/extension-font-family";
import ImageResize from "tiptap-extension-resize-image";
import { useEditor, EditorContent } from "@tiptap/react";
import TableHeader from "@tiptap/extension-table-header";

import { Ruler } from "./ruler";

// import { useEditorStore } from "@/store/use-editor-store";

export const Editor = ({ initialContent }) => {
  const leftMargin = 56;
  const rightMargin = 56;

  // const { setEditor } = useEditorStore();

  const editor = useEditor({
    autofocus: true,
    immediatelyRender: false,
    onCreate({ editor }) {
      // setEditor(editor);
    },
    onDestroy() {
     // setEditor(null);
    },
    onUpdate({ editor }) {
     // setEditor(editor);
    },
    onSelectionUpdate({ editor }) {
     // setEditor(editor);
    },
    onTransaction({ editor }) {
     // setEditor(editor);
    },
    onBlur({ editor }) {
     // setEditor(editor);
    },
    onContentError({ editor }) {
    // setEditor(editor);
    },
    editorProps: {
      attributes: {
        style: `padding-left: ${leftMargin}px; padding-right: ${rightMargin}px`,
        class:
          "focus:outline-none print:border-0 bg-white border border-[#C7C7C7] flex flex-col min-h-[297mm] w-[816px] pt-10 pr-14 pb-10 cursor-text",
      },
    },
    extensions: [
      StarterKit.configure({
        history: false,
      }),
      TaskList,
      Pagination,
      TaskItem.configure({ nested: true }),
      Table.configure({ resizable: true }),
      TableRow,
      TableHeader,
      TableCell,
      Image,
      ImageResize,
      Underline,
      FontFamily,
      TextStyle,
      Highlight.configure({ multicolor: true }),
      Color,
      Link.configure({
        openOnClick: false,
        autolink: true,
        defaultProtocol: "https",
      }),
      TextAlign.configure({ types: ["heading", "paragraph"] }),
    ],
    content: "<p>Hello World! 🌎️</p>",
  });

  return (
    <div className="size-full overflow-x-auto bg-[#F9FBFD] px-4 print:p-0 print:bg-white print:overflow-visible">
      <div className="min-w-max flex flex-col items-center w-full py-4 print:py-0 mx-auto print:w-full print:min-w-0">
        <EditorContent editor={editor} />
      </div>
    </div>
  );
};

**Comment by hugs7** [comment]
Have a look at my example in the readme. You need both the Pagination extension and the PageNode too (this is a named import from my package)

**Comment by gillangit** [comment]
`import PaginationExtension, { PageNode } from "tiptap-extension-pagination";`

and i use ini extentions:
`    extensions: [
      StarterKit.configure({
        history: false,
      }),
      PaginationExtension,
      PageNode,]`

and then showing erro RangeError: There is no position before the top-level node

**Comment by hugs7** [comment]
Ah that is a bug when you have an empty document. Am fixing this at the moment

**Comment by hugs7** [comment]
@gillangit fixed in #4

**Comment by gillangit** [comment]
![image](https://github.com/user-attachments/assets/c0f29f9d-fa1d-47e2-a8db-5569e3af4625)
very nice, im using 
`    "tiptap-extension-pagination": "^1.3.0-alpha.5"`
 mini bug with my class, they have 2 page and only working in dark mode..
 thanks bro

**Comment by hugs7** [comment]
Yeah I need to fix that. Can you raise an issue for the paper colour
